name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow only one concurrent deployment
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0'
          bundler-cache: true
      
      - name: Install dependencies
        run: bundle install
      
      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      
      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        run: |
          # Set up credentials for external repository
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Create CNAME file
          echo "bruno.foundation" > _site/CNAME
          
          # Go to build directory
          cd _site
          
          # Initialize git repo in output directory
          git init
          git add -A
          git commit -m "Deploy Jekyll site from Actions"
          
          # Force push to destination repository using GITHUB_TOKEN
          git push -f https://${{ secrets.GH_PAT }}@github.com/brunogama/brunogama.github.io.git main
        env:
          JEKYLL_ENV: production