name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # or master, whichever is your default branch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write  # Changed from read to write to allow pushing to gh-pages
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.0' # Use a version that GitHub Pages supports
          bundler-cache: true # Speeds up subsequent runs
        
      - name: Install dependencies
        run: |
          bundle config set --local path vendor/bundle
          bundle install
        
      - name: Build site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          cname: bruno.foundation